SELECT Nome
  FROM TURMA JOIN ALUNO_TURMA JOIN ALUNO ON (TURMA.id=ALUNO_TURMA.turma_id AND ALUNO_TURMA.aluno_id=ALUNO.id)
  WHERE PROFESSOR_id IN (SELECT id FROM PROFESSOR WHERE nome = 'JOAO PEDRO')

SELECT DISTINCT dia_da_semana
  FROM TURMA
  WHERE DISCIPLINA_id IN (SELECT id FROM DISCIPLINA WHERE nome = 'MATEMATICA')

SELECT Nome
  FROM TURMA JOIN ALUNO_TURMA JOIN ALUNO ON (TURMA.id=ALUNO_TURMA.turma_id AND ALUNO_TURMA.aluno_id=ALUNO.id)
  WHERE DISCIPLINA_id IN (SELECT id FROM DISCIPLINA WHERE nome = 'MATEMATICA' AND nome = 'FISICA')
