SELECT Nome
  FROM ALUNO JOIN ALUNO_TURMA JOIN TURMA ON (ALUNO.id=ALUNO_TURMA.aluno_id AND ALUNO_TURMA.turma_id=TURMA.id)
  WHERE PROFESSOR_id IN (SELECT id FROM PROFESSOR WHERE nome = 'JOAO PEDRO')

SELECT DISTINCT dia_da_semana
  FROM TURMA
  WHERE DISCIPLINA_id IN (SELECT id FROM DISCIPLINA WHERE nome = 'MATEMATICA')

SELECT Nome
  FROM ALUNO JOIN ALUNO_TURMA JOIN TURMA ON (ALUNO.id=ALUNO_TURMA.aluno_id AND ALUNO_TURMA.turma_id=TURMA.id)
  WHERE DISCIPLINA_id IN (SELECT id FROM DISCIPLINA WHERE nome = 'MATEMATICA' AND nome = 'FISICA')

SELECT nome
  FROM DISCIPLINA
  WHERE id NOT IN (SELECT DISCIPLINA_id FROM TURMA)

SELECT Nome
  FROM ALUNO JOIN ALUNO_TURMA JOIN TURMA ON (ALUNO.id=ALUNO_TURMA.aluno_id AND ALUNO_TURMA.turma_id=TURMA.id)
  WHERE DISCIPLINA_id IN (SELECT id FROM DISCIPLINA WHERE nome = 'MATEMATICA') AND NOT IN ()
